//export const API_URL = "http://localhost:8000";
//export const API_URL = "http://134.122.82.97:8000";
export const API_URL = "https://omercan-task.herokuapp.com";

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const LOGGED_IN = 'LOGGED_IN';
export const NOT_LOGGED_IN = 'NOT_LOGGED_IN';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const PROFILE_USER_REQUEST = 'PROFILE_USER_REQUEST';
export const PROFILE_USER_SUCCESS = 'PROFILE_USER_SUCCESS';
export const PROFILE_USER_FAILED = 'PROFILE_USER_FAILED';

export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAILED = 'TASK_LIST_FAILED';

export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST';
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS';
export const TASK_ADD_FAILED = 'TASK_ADD_FAILED';

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST';
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS';
export const TASK_UPDATE_FAILED = 'TASK_UPDATE_FAILED';

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAILED = 'TASK_DELETE_FAILED';
